/* 실제 데이터 */
const movies = [
    {
        popularity: 104.397,
        vote_count: 4,
        video: false,
        poster_path: '/k68nPLbIST6NP96JmTxmZijEvCA.jpg',
        id: 577922,
        adult: false,
        backdrop_path: '/wzJRB4MKi3yK138bJyuL9nx47y6.jpg',
        original_language: 'en',
        original_title: 'Tenet',
        genre_ids: [28, 53],
        title: 'Tenet',
        vote_average: 5,
        overview:
            'Armed with only one word - Tenet - and fighting for the survival of the entire world, the Protagonist journeys through a twilight world of international espionage on a mission that will unfold in something beyond real time.',
        release_date: '2020-08-26',
    },
    {
        popularity: 97.043,
        vote_count: 98,
        video: false,
        poster_path: '/5MSDwUcqnGodFTvtlLiLKK0XKS.jpg',
        id: 521034,
        adult: false,
        backdrop_path: '/8PK4X8U3C79ilzIjNTkTgjmc4js.jpg',
        original_language: 'en',
        original_title: 'The Secret Garden',
        genre_ids: [18, 14, 10751],
        title: 'The Secret Garden',
        vote_average: 7.3,
        overview:
            'Mary Lennox is born in India to wealthy British parents who never wanted her. When her parents suddenly die, she is sent back to England to live with her uncle. She meets her sickly cousin, and the two children find a wondrous secret garden lost in the grounds of Misselthwaite Manor.',
        release_date: '2020-07-08',
    },
    {
        popularity: 79.152,
        vote_count: 26871,
        video: false,
        poster_path: '/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg',
        id: 27205,
        adult: false,
        backdrop_path: '/s3TBrRGB1iav7gFOCNx3H31MoES.jpg',
        original_language: 'en',
        original_title: 'Inception',
        genre_ids: [28, 12, 878],
        title: 'Inception',
        vote_average: 8.3,
        overview:
            'Cobb, a skilled thief who commits corporate espionage by infiltrating the subconscious of his targets is offered a chance to regain his old life as payment for a task considered to be impossible: "inception", the implantation of another person\'s idea into a target\'s subconscious.',
        release_date: '2010-07-15',
    },
    {
        popularity: 55.055,
        vote_count: 30,
        video: false,
        poster_path: '/dKjD3DTZjRI3Ipkf7Oz5zAILnwD.jpg',
        id: 659991,
        adult: false,
        backdrop_path: '/5nRyaVklxyA9OkxqZaPv1KBRqpd.jpg',
        original_language: 'en',
        original_title: 'Made in Italy',
        genre_ids: [35, 18],
        title: 'Made in Italy',
        vote_average: 6.3,
        overview:
            'A bohemian artist travels from London to Italy with his estranged son to sell the house they inherited from his late wife.',
        release_date: '2020-08-06',
    },
    {
        popularity: 71.55,
        vote_count: 457,
        video: false,
        poster_path: '/jHo2M1OiH9Re33jYtUQdfzPeUkx.jpg',
        id: 385103,
        adult: false,
        backdrop_path: '/fKtYXUhX5fxMxzQfyUcQW9Shik6.jpg',
        original_language: 'en',
        original_title: 'Scoob!',
        genre_ids: [12, 16, 35, 10751],
        title: 'Scoob!',
        vote_average: 7.5,
        overview:
            'In Scooby-Doo’s greatest adventure yet, see the never-before told story of how lifelong friends Scooby and Shaggy first met and how they joined forces with young detectives Fred, Velma, and Daphne to form the famous Mystery Inc. Now, with hundreds of cases solved, Scooby and the gang face their biggest, toughest mystery ever: an evil plot to unleash the ghost dog Cerberus upon the world. As they race to stop this global “dogpocalypse,” the gang discovers that Scooby has a secret legacy and an epic destiny greater than anyone ever imagined.',
        release_date: '2020-07-08',
    },
    {
        popularity: 81.806,
        vote_count: 5,
        video: false,
        poster_path: '/9wKaK8gpCMGhU2AHxknt1fa4jP0.jpg',
        id: 581526,
        adult: false,
        backdrop_path: '/pLHeRaGgy2e9qeTviZZfbWYqZ3s.jpg',
        original_language: 'ko',
        original_title: '다만 악에서 구하소서',
        genre_ids: [28, 80],
        title: 'Deliver Us from Evil',
        vote_average: 6,
        overview:
            'In-nam (HWANG Jung-min) is a Korean hitman living in Japan who completes what he has decided will be his final job. But soon after, he learns that the daughter of a woman from his past (CHOI Hee-seo), who now lives in Thailand, has been kidnapped. He heads to Southeast Asia to find the child, after a brief stop in Incheon, where he is helped by the bar worker Yoo-yi (PARK Jung-min). However, he has not reached Thailand alone, as on his trail is the vicious gangster Ray (LEE Jung-jae), whose brother was recently assassinated by In-nam.',
        release_date: '2020-08-05',
    },
    {
        popularity: 53.277,
        vote_count: 17803,
        video: false,
        poster_path: '/wuMc08IPKEatf9rnMNXvIDxqP4W.jpg',
        id: 671,
        adult: false,
        backdrop_path: '/hziiv14OpD73u9gAak4XDDfBKa2.jpg',
        original_language: 'en',
        original_title: "Harry Potter and the Philosopher's Stone",
        genre_ids: [12, 14, 10751],
        title: "Harry Potter and the Philosopher's Stone",
        vote_average: 7.9,
        overview:
            "Harry Potter has lived under the stairs at his aunt and uncle's house his whole life. But on his 11th birthday, he learns he's a powerful wizard -- with a place waiting for him at the Hogwarts School of Witchcraft and Wizardry. As he learns to harness his newfound powers with the help of the school's kindly headmaster, Harry uncovers the truth about his parents' deaths -- and about the villain who's to blame.",
        release_date: '2001-11-16',
    },
    {
        popularity: 60.351,
        vote_count: 8845,
        video: false,
        poster_path: '/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
        id: 496243,
        adult: false,
        backdrop_path: '/ApiBzeaa95TNYliSbQ8pJv4Fje7.jpg',
        original_language: 'ko',
        original_title: '기생충',
        genre_ids: [35, 18, 53],
        title: 'Parasite',
        vote_average: 8.5,
        overview:
            "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
        release_date: '2019-05-30',
    },
    {
        popularity: 56.845,
        vote_count: 86,
        video: false,
        poster_path: '/3eg0kGC2Xh0vhydJHO37Sp4cmMt.jpg',
        id: 531499,
        adult: false,
        backdrop_path: '/zogWnCSztU8xvabaepQnAwsOtOt.jpg',
        original_language: 'en',
        original_title: 'The Tax Collector',
        genre_ids: [28, 80, 18],
        title: 'The Tax Collector',
        vote_average: 5.9,
        overview:
            'David Cuevas is a family man who works as a gangland tax collector for high ranking Los Angeles gang members. He makes collections across the city with his partner Creeper making sure people pay up or will see retaliation. An old threat returns to Los Angeles that puts everything David loves in harm’s way.',
        release_date: '2020-08-07',
    },
    {
        popularity: 40.939,
        vote_count: 4,
        video: false,
        poster_path: '/mMICdcRBxiEUUpdAFCYRezE3Dy5.jpg',
        id: 523781,
        adult: false,
        backdrop_path: '/q7z2kKGeAfkKQx6cmb4pFcEEkME.jpg',
        original_language: 'en',
        original_title: 'Words on Bathroom Walls',
        genre_ids: [18],
        title: 'Words on Bathroom Walls',
        vote_average: 1.9,
        overview:
            'The story follows a student navigating high school life while living with paranoid schizophrenia and battling wild hallucinations. An experimental drug trial promises to help hide his illness from his peers and, most importantly, from the girl of his dreams.',
        release_date: '2020-08-21',
    },
    {
        popularity: 42.935,
        vote_count: 5,
        video: false,
        poster_path: '/3HvqVuCDcq6DTN2aAvOEOfgyzXi.jpg',
        id: 582885,
        adult: false,
        backdrop_path: '/uyg0eleNHHyr8LjaE61FgeUsMRc.jpg',
        original_language: 'fr',
        original_title: 'Mignonnes',
        genre_ids: [35, 18],
        title: 'Cuties',
        vote_average: 3.8,
        overview:
            'Amy, an 11-year-old girl, joins a group of dancers named “the cuties” at school, and rapidly grows aware of her burgeoning femininity—upsetting her mother and her values in the process.',
        release_date: '2020-08-19',
    },
    {
        popularity: 57.29,
        vote_count: 13,
        video: false,
        poster_path: '/jYoRYxB56YU7CmqU4BfDWIuHZUX.jpg',
        id: 390635,
        adult: false,
        backdrop_path: '/mWb5UjxCmevMlvbxnXc9Y3zc00w.jpg',
        original_language: 'ja',
        original_title: "劇場版 Fate／stay night [Heaven's Feel] III.spring song",
        genre_ids: [16],
        title: "Fate/Stay Night: Heaven's Feel III. Spring Song",
        vote_average: 4.2,
        overview:
            'Theatrical-release adaptation of the visual novel "Fate/stay night", following the third and final route. (Final part of a trilogy.)',
        release_date: '2020-08-15',
    },
    {
        popularity: 56.693,
        vote_count: 44,
        video: false,
        poster_path: '/7I8BmtqjLyyMf3EjrUEIQs0gFYw.jpg',
        id: 625568,
        adult: false,
        backdrop_path: '/e7bpDu3RKsjOYLSt9gHYT2c32Zd.jpg',
        original_language: 'en',
        original_title: 'Unhinged',
        genre_ids: [28, 53],
        title: 'Unhinged',
        vote_average: 6.6,
        overview:
            'A case of road rage turns into full-blown terror when an unstable driver follows a woman and her son.',
        release_date: '2020-07-02',
    },
    {
        popularity: 56.475,
        vote_count: 91,
        video: false,
        poster_path: '/zQFjMmE3K9AX5QrBL1SXIxYQ9jz.jpg',
        id: 579583,
        adult: false,
        backdrop_path: '/5rwcd24GGltKiqdPT4G2dmchLr9.jpg',
        original_language: 'en',
        original_title: 'The King of Staten Island',
        genre_ids: [35, 18],
        title: 'The King of Staten Island',
        vote_average: 6.7,
        overview:
            'Scott has been a case of arrested development ever since his firefighter father died when he was seven. He’s now reached his mid-20s having achieved little, chasing a dream of becoming a tattoo artist that seems far out of reach. As his ambitious younger sister heads off to college, Scott is still living with his exhausted ER nurse mother and spends his days smoking weed, hanging with the guys — Oscar, Igor and Richie — and secretly hooking up with his childhood friend Kelsey. But when his mother starts dating a loudmouth firefighter named Ray, it sets off a chain of events that will force Scott to grapple with his grief and take his first tentative steps toward moving forward in life.',
        release_date: '2020-07-22',
    },
    {
        popularity: 65.343,
        vote_count: 16,
        video: false,
        poster_path: '/v0guO0krvyz8IfKGxEje04LVM9d.jpg',
        id: 517412,
        adult: false,
        backdrop_path: '/4tphk3VbqoRtCVuOzlEQxUrpR6c.jpg',
        original_language: 'en',
        original_title: 'Tesla',
        genre_ids: [18, 36],
        title: 'Tesla',
        vote_average: 6,
        overview:
            'The story of the Promethean struggles of Nikola Tesla, as he attempts to transcend entrenched technology—including his own previous work—by pioneering a system of wireless energy that would change the world.',
        release_date: '2020-08-14',
    },
    {
        popularity: 66.399,
        vote_count: 9,
        video: false,
        poster_path: '/izGiAbtC2lmGk3bbV5t3OowJhtP.jpg',
        id: 595148,
        adult: false,
        backdrop_path: '/eZ8eK0moqUo6Vwq08OK1POfyUF5.jpg',
        original_language: 'en',
        original_title: 'Irresistible',
        genre_ids: [35, 18],
        title: 'Irresistible',
        vote_average: 5.2,
        overview:
            'A Democratic political consultant helps a retired Marine colonel run for mayor in a small, conservative Wisconsin town.',
        release_date: '2020-08-21',
    },
    {
        popularity: 47.412,
        vote_count: 145,
        video: false,
        poster_path: '/eV4HVz2m27fJ2VqZwzZd4Yf8Tli.jpg',
        id: 575479,
        adult: false,
        backdrop_path: '/tJkjdZguScL7aZrHvgOma7rhu8c.jpg',
        original_language: 'fr',
        original_title: 'Une fille facile',
        genre_ids: [35, 18],
        title: 'An Easy Girl',
        vote_average: 5.7,
        overview:
            'Naïma has just turned 16. This summer, she will have to decide what she wants from life if she doesn’t want to miss out. Then her cousin Sofia arrives, with an amazing body and a dangerously seductive lifestyle. Naïma desires only to follow her own path, so long as it leads upwards… Despite the warnings of her best friend Dodo, she and Sofia will live through unforgettable encounters during a long summer that will mark them forever',
        release_date: '2019-08-28',
    },
    {
        popularity: 43.178,
        vote_count: 121,
        video: false,
        poster_path: '/3ynPnBXQVT2Y0s19fDIPlWKUlxH.jpg',
        id: 587496,
        adult: false,
        backdrop_path: '/2gBMBfmQvHeOQQ5PiKiuxVdGs77.jpg',
        original_language: 'en',
        original_title: 'The Rental',
        genre_ids: [18, 27, 53],
        title: 'The Rental',
        vote_average: 5.6,
        overview:
            'Two couples on an oceanside getaway grow suspicious that the host of their seemingly perfect rental house may be spying on them. Before long, what should have been a celebratory weekend trip turns into something far more sinister.',
        release_date: '2020-07-23',
    },
    {
        popularity: 43.987,
        vote_count: 3,
        video: false,
        poster_path: '/8siHWeEQB5vwGVYIafxbsbeyyJo.jpg',
        id: 605798,
        adult: false,
        backdrop_path: '/vnJ9FioBkVxiAwEuFMhYQdHRnm1.jpg',
        original_language: 'en',
        original_title: 'How to Fake a War',
        genre_ids: [],
        title: 'How to Fake a War',
        vote_average: 1.3,
        overview:
            'When an unexpected outbreak of peace leads to a ceasefire between Russian forces and Georgian rebels, arrogant rock star Harry Hope fears for the success of his heavily hyped Piece of Peace global charity concert. Desperate, he dispatches his PR consultant, Kate, and her naïve intern, Peggy, to create a fake war story – until the concert, at least.',
        release_date: '2020-08-21',
    },
    {
        popularity: 47.664,
        vote_count: 9,
        video: false,
        poster_path: '/j8MRnCjuN7kpM8w3B5hM5mrvTaE.jpg',
        id: 400160,
        adult: false,
        backdrop_path: '/wu1uilmhM4TdluKi2ytfz8gidHf.jpg',
        original_language: 'en',
        original_title: 'The SpongeBob Movie: Sponge on the Run',
        genre_ids: [12, 16, 35, 14, 10751],
        title: 'The SpongeBob Movie: Sponge on the Run',
        vote_average: 7.4,
        overview:
            "After SpongeBob's beloved pet snail Gary is snail-napped, he and Patrick embark on an epic adventure to The Lost City of Atlantic City to bring Gary home.",
        release_date: '2020-08-14',
    },
    {
        popularity: 38.187,
        vote_count: 2,
        video: false,
        poster_path: '/rBrwaANEz4uSqxUjBKKGh8eS0rt.jpg',
        id: 672035,
        adult: false,
        backdrop_path: '/98mCjIVLdGCn6WHtEnPKT8QwBpv.jpg',
        original_language: 'en',
        original_title: 'You Cannot Kill David Arquette',
        genre_ids: [99],
        title: 'You Cannot Kill David Arquette',
        vote_average: 1.5,
        overview:
            'Following his infamous championship as part of a marketing stunt for the film Ready to Rumble, David Arquette is widely known as the most hated man in pro-wrestling worldwide. Nearly 20 years after he "won" the initial title, through ups and downs in his career, with his family, and with his struggles with addiction, David Arquette seeks redemption by returning to the ring...for real this time.',
        release_date: '2020-08-21',
    },
    {
        popularity: 40.524,
        vote_count: 2888,
        video: false,
        poster_path: '/f4aul3FyD3jv3v4bul1IrkWZvzq.jpg',
        id: 508439,
        adult: false,
        backdrop_path: '/xFxk4vnirOtUxpOEWgA1MCRfy6J.jpg',
        original_language: 'en',
        original_title: 'Onward',
        genre_ids: [12, 16, 35, 14, 10751],
        title: 'Onward',
        vote_average: 7.9,
        overview:
            'In a suburban fantasy world, two teenage elf brothers embark on an extraordinary quest to discover if there is still a little magic left out there.',
        release_date: '2020-02-29',
    },
    {
        popularity: 31.652,
        vote_count: 4,
        video: false,
        poster_path: '/hgeXCLiRNd26fkoxBmjyroTtunc.jpg',
        id: 726876,
        adult: false,
        backdrop_path: '/49CyXZdGovyXgaGw4e9P0GNYzvE.jpg',
        original_language: 'en',
        original_title: 'Behind the Line: Escape to Dunkirk',
        genre_ids: [10752],
        title: 'Behind the Line: Escape to Dunkirk',
        vote_average: 1.3,
        overview:
            "Occupied France, 1940. A Nazi Commander discovers one of his prisoners, Danny is a champion boxer. He forces him to fight for his company's entertainment. But the POWs realise they can use these contests, as cover for an audacious breakout, before they re sent to Germany, where escape will be almost impossible. Their fate and freedom may all come down to how long Danny can keep fighting.",
        release_date: '2020-08-20',
    },
    {
        popularity: 47.051,
        vote_count: 5418,
        video: false,
        poster_path: '/aQvJ5WPzZgYVDrxLX4R6cLJCEaQ.jpg',
        id: 454626,
        adult: false,
        backdrop_path: '/stmYfCUGd8Iy6kAMBr6AmWqx8Bq.jpg',
        original_language: 'en',
        original_title: 'Sonic the Hedgehog',
        genre_ids: [28, 35, 878, 10751],
        title: 'Sonic the Hedgehog',
        vote_average: 7.5,
        overview:
            'Based on the global blockbuster videogame franchise from Sega, Sonic the Hedgehog tells the story of the world’s speediest hedgehog as he embraces his new home on Earth. In this live-action adventure comedy, Sonic and his new best friend team up to defend the planet from the evil genius Dr. Robotnik and his plans for world domination.',
        release_date: '2020-02-12',
    },
    {
        popularity: 58.113,
        vote_count: 3,
        video: false,
        poster_path: '/shx7pGYQ9s4t7WFe19eES2WOrMS.jpg',
        id: 610201,
        adult: false,
        backdrop_path: '/lvtEcdBmmrxzAQvRIYyDRQDeDJM.jpg',
        original_language: 'en',
        original_title: 'The Pale Door',
        genre_ids: [27, 37],
        title: 'The Pale Door',
        vote_average: 4.3,
        overview:
            'After a train robbery, two brothers leading a gang of cowboys must survive the night in a ghost town inhabited by a coven of witches.',
        release_date: '2020-08-21',
    },
    {
        popularity: 41.357,
        vote_count: 4,
        video: false,
        poster_path: '/uOw5JD8IlD546feZ6oxbIjvN66P.jpg',
        id: 718444,
        adult: false,
        backdrop_path: '/yfFkvxPXY5RSsZVQBF8G3JwtWXs.jpg',
        original_language: 'en',
        original_title: 'Rogue',
        genre_ids: [28],
        title: 'Rogue',
        vote_average: 5.3,
        overview:
            'Battle-hardened O’Hara leads a lively mercenary team of soldiers on a daring mission: rescue hostages from their captors in remote Africa. But as the mission goes awry and the team is stranded, O’Hara’s squad must face a bloody, brutal encounter with a gang of rebels.',
        release_date: '2020-08-20',
    },
    {
        popularity: 37.165,
        vote_count: 440,
        video: false,
        poster_path: '/yf5IuMW6GHghu39kxA0oFx7Bxmj.jpg',
        id: 587792,
        adult: false,
        backdrop_path: '/d7JUXVvjvVCXWs1mlpyO5ESdWdT.jpg',
        original_language: 'en',
        original_title: 'Palm Springs',
        genre_ids: [35, 14, 9648, 10749],
        title: 'Palm Springs',
        vote_average: 7.6,
        overview:
            'When carefree Nyles and reluctant maid of honor Sarah have a chance encounter at a Palm Springs wedding, things get complicated when they find themselves unable to escape the venue, themselves, or each other.',
        release_date: '2020-07-10',
    },
    {
        popularity: 50.211,
        vote_count: 6159,
        video: false,
        poster_path: '/iZf0KyrE25z1sage4SYFLCCrMi9.jpg',
        id: 530915,
        adult: false,
        backdrop_path: '/cqa3sa4c4jevgnEJwq3CMF8UfTG.jpg',
        original_language: 'en',
        original_title: '1917',
        genre_ids: [28, 18, 36, 10752],
        title: '1917',
        vote_average: 8,
        overview:
            'At the height of the First World War, two young British soldiers must cross enemy territory and deliver a message that will stop a deadly attack on hundreds of soldiers.',
        release_date: '2019-12-25',
    },
    {
        popularity: 29.966,
        vote_count: 4,
        video: false,
        poster_path: '/mliD95nVqBijPGQdZ3xcg8Nsagu.jpg',
        id: 541100,
        adult: false,
        backdrop_path: '/3CRqN7QfY43vp920P3GxBIQwC92.jpg',
        original_language: 'en',
        original_title: 'Thriller',
        genre_ids: [27],
        title: 'Thriller',
        vote_average: 4.5,
        overview:
            'Years after a childhood prank goes horribly wrong, a clique of South Central LA teens find themselves terrorized during Homecoming weekend by a killer hell-bent on revenge.',
        release_date: '2020-08-20',
    },
    {
        popularity: 51.378,
        vote_count: 4,
        video: false,
        poster_path: '/xZCsQe59lohNnvOZzPH46A7Pj2P.jpg',
        id: 675490,
        adult: false,
        backdrop_path: null,
        original_language: 'en',
        original_title: 'The Unfamiliar',
        genre_ids: [27, 53],
        title: 'The Unfamiliar',
        vote_average: 3.6,
        overview:
            'A British Army doctor comes back from a war, thinking that she has PTSD only to discover that there is a more daunting malevolence at work making the life that she knew unfamiliar.',
        release_date: '2020-08-20',
    },
    {
        popularity: 42.379,
        vote_count: 1277,
        video: false,
        poster_path: '/wxPhn4ef1EAo5njxwBkAEVrlJJG.jpg',
        id: 514847,
        adult: false,
        backdrop_path: '/qfQ78ZKiouoM2yhAnfNblp9ijQE.jpg',
        original_language: 'en',
        original_title: 'The Hunt',
        genre_ids: [28, 27, 53],
        title: 'The Hunt',
        vote_average: 6.6,
        overview:
            "Twelve strangers wake up in a clearing. They don't know where they are—or how they got there. In the shadow of a dark internet conspiracy theory, ruthless elitists gather at a remote location to hunt humans for sport. But their master plan is about to be derailed when one of the hunted turns the tables on her pursuers.",
        release_date: '2020-03-11',
    },
    {
        popularity: 42.161,
        vote_count: 293,
        video: false,
        poster_path: '/hPkqY2EMqWUnFEoedukilIUieVG.jpg',
        id: 531876,
        adult: false,
        backdrop_path: '/n1RohH2VoK1CdVI2fXvcP19dSlm.jpg',
        original_language: 'en',
        original_title: 'The Outpost',
        genre_ids: [28, 18, 36, 10752],
        title: 'The Outpost',
        vote_average: 6.6,
        overview:
            'A small unit of U.S. soldiers, alone at the remote Combat Outpost Keating, located deep in the valley of three mountains in Afghanistan, battles to defend against an overwhelming force of Taliban fighters in a coordinated attack. The Battle of Kamdesh, as it was known, was the bloodiest American engagement of the Afghan War in 2009 and Bravo Troop 3-61 CAV became one of the most decorated units of the 19-year conflict.',
        release_date: '2020-06-24',
    },
    {
        popularity: 52.94,
        vote_count: 5,
        video: false,
        poster_path: '/5pe30v0z4ucVgwh5nR439cCzwwO.jpg',
        id: 632618,
        adult: false,
        backdrop_path: '/cVdYaAQmd5DZNdo0KFJruz7JpUs.jpg',
        original_language: 'es',
        original_title: 'Crímenes de familia',
        genre_ids: [80, 18, 53],
        title: 'The Crimes That Bind',
        vote_average: 7.4,
        overview:
            'When her son is accused of raping and trying to murder his ex-wife, Alicia embarks on a journey that will change her life forever.',
        release_date: '2020-08-20',
    },
    {
        popularity: 35.816,
        vote_count: 2,
        video: false,
        poster_path: '/m7B8kVDlbiNI2XTnRhw6Fbc53dX.jpg',
        id: 717676,
        adult: false,
        backdrop_path: null,
        original_language: 'en',
        original_title: 'Tulsa',
        genre_ids: [35, 18],
        title: 'Tulsa',
        vote_average: 5,
        overview:
            'A desperate marine biker’s life is turned upside-down when he is united with the sassy 9-year-old daughter he never knew existed.',
        release_date: '2020-08-21',
    },
    {
        popularity: 35.662,
        vote_count: 26,
        video: false,
        poster_path: '/A3z0KMLIEGL22mVrgaV7KDxKRmT.jpg',
        id: 539885,
        adult: false,
        backdrop_path: '/ekkuqt9Q2ad1F7xq2ZONP0oq36P.jpg',
        original_language: 'en',
        original_title: 'Ava',
        genre_ids: [28, 80, 18, 9648, 53],
        title: 'Ava',
        vote_average: 5.5,
        overview:
            'A black ops assassin is forced to fight for her own survival after a job goes dangerously wrong.',
        release_date: '2020-08-06',
    },
    {
        popularity: 42.564,
        vote_count: 367,
        video: false,
        poster_path: '/MBiKqTsouYqAACLYNDadsjhhC0.jpg',
        id: 486589,
        adult: false,
        backdrop_path: '/bga3i5jcejBekr2FCGJga1fYCh.jpg',
        original_language: 'en',
        original_title: 'Red Shoes and the Seven Dwarfs',
        genre_ids: [16, 10749, 10751],
        title: 'Red Shoes and the Seven Dwarfs',
        vote_average: 7.3,
        overview:
            'Princes who have been turned into Dwarfs seek the red shoes of a lady in order to break the spell, although it will not be easy.',
        release_date: '2019-07-25',
    },
    {
        popularity: 32.713,
        vote_count: 0,
        video: false,
        poster_path: '/xrI4EnZWftpo1B7tTvlMUXVOikd.jpg',
        id: 340102,
        adult: false,
        backdrop_path: '/lNhKmIG5Kw2qYG3REYuwmNUgl0n.jpg',
        original_language: 'en',
        original_title: 'The New Mutants',
        genre_ids: [28, 12, 27, 878],
        title: 'The New Mutants',
        vote_average: 0,
        overview:
            'Five young mutants, just discovering their abilities while held in a secret facility against their will, fight to escape their past sins and save themselves.',
        release_date: '2020-08-26',
    },
    {
        popularity: 23.935,
        vote_count: 2,
        video: false,
        poster_path: '/oiYwsXiHKjNkKTXL2DIZzgvmrxQ.jpg',
        id: 649392,
        adult: false,
        backdrop_path: '/yvuy1lKG0sgSkTxOACX8el3MHoQ.jpg',
        original_language: 'en',
        original_title: 'Rev',
        genre_ids: [28, 18],
        title: 'Rev',
        vote_average: 2,
        overview:
            'A young thief with a history of grand theft auto becomes an informant and helps police bring down a criminal enterprise involved in the smuggling of hundreds of exotic super cars.',
        release_date: '2020-08-20',
    },
    {
        popularity: 29.889,
        vote_count: 55,
        video: false,
        poster_path: '/95S6PinQIvVe4uJAd82a2iGZ0rA.jpg',
        id: 522444,
        adult: false,
        backdrop_path: '/fRrpOILyXuWaWLmqF7kXeMVwITQ.jpg',
        original_language: 'en',
        original_title: 'Black Water: Abyss',
        genre_ids: [12, 27, 53],
        title: 'Black Water: Abyss',
        vote_average: 5.5,
        overview:
            'An adventure-loving couple convince their friends to explore a remote, uncharted cave system in the forests of Northern Australia. With a tropical storm approaching, they abseil into the mouth of the cave, but when the caves start to flood, tensions rise as oxygen levels fall and the friends find themselves trapped. Unknown to them, the storm has also brought in a pack of dangerous and hungry crocodiles.',
        release_date: '2020-07-09',
    },
    {
        popularity: 38.573,
        vote_count: 1057,
        video: false,
        poster_path: '/7W0G3YECgDAfnuiHG91r8WqgIOe.jpg',
        id: 446893,
        adult: false,
        backdrop_path: '/qsxhnirlp7y4Ae9bd11oYJSX59j.jpg',
        original_language: 'en',
        original_title: 'Trolls World Tour',
        genre_ids: [12, 16, 35, 14, 10402, 10751],
        title: 'Trolls World Tour',
        vote_average: 7.6,
        overview:
            'Queen Poppy and Branch make a surprising discovery — there are other Troll worlds beyond their own, and their distinct differences create big clashes between these various tribes. When a mysterious threat puts all of the Trolls across the land in danger, Poppy, Branch, and their band of friends must embark on an epic quest to create harmony among the feuding Trolls to unite them against certain doom.',
        release_date: '2020-03-12',
    },
    {
        popularity: 30.826,
        vote_count: 17,
        video: false,
        poster_path: '/27eA9xGba61LtKr7gJRnhtDDgEP.jpg',
        id: 651586,
        adult: false,
        backdrop_path: '/1iEDKZHREDetZcOoqioZewcHOw9.jpg',
        original_language: 'es',
        original_title: 'Superagente Makey',
        genre_ids: [28, 35],
        title: 'Superagente Makey',
        vote_average: 3.9,
        overview:
            'Makey is a humble police officer that, unexpectedly, gets caught in the middle of a dangerous international drug operation in the Costa del Sol, Spain.',
        release_date: '2020-07-17',
    },
    {
        popularity: 39.697,
        vote_count: 43,
        video: false,
        poster_path: '/tPcYPMTOXgIZGUCB5S6nV0yHuD3.jpg',
        id: 581392,
        adult: false,
        backdrop_path: '/aWsVwgG324dFQS5xHEjB7OCOT9w.jpg',
        original_language: 'ko',
        original_title: '반도',
        genre_ids: [28, 27, 53],
        title: 'Peninsula',
        vote_average: 5.9,
        overview:
            'A soldier and his team battle hordes of post-apocalyptic zombies in the wastelands of the Korean Peninsula.',
        release_date: '2020-07-15',
    },
    {
        popularity: 26.263,
        vote_count: 175,
        video: false,
        poster_path: '/7Jk4pDMM3G9h29lWshEZjX711wg.jpg',
        id: 605804,
        adult: false,
        backdrop_path: '/su0huGwZfAmzPvUjnlG42LO9GFl.jpg',
        original_language: 'en',
        original_title: 'The Wretched',
        genre_ids: [27],
        title: 'The Wretched',
        vote_average: 6.3,
        overview:
            "A rebellious teenage boy, struggling with his parent's imminent divorce, encounters a terrifying evil after his next-door neighbor becomes possessed by an ancient witch that feasts on children.",
        release_date: '2020-05-01',
    },
    {
        popularity: 26.696,
        vote_count: 2,
        video: false,
        poster_path: '/i8cfql14qOSYb1d1B9K1phgVtyA.jpg',
        id: 683510,
        adult: false,
        backdrop_path: '/sWmdL0VGeAHt5Xeok3hmJBymIGs.jpg',
        original_language: 'en',
        original_title: 'Riverdance 25th Anniversary Show',
        genre_ids: [10402],
        title: 'Riverdance 25th Anniversary Show',
        vote_average: 4.5,
        overview:
            'A powerful and stirring reinvention of the show, celebrated the world over for its Grammy Award-winning music and the thrilling energy and passion of its Irish and international dance.',
        release_date: '2020-08-21',
    },
    {
        popularity: 30.709,
        vote_count: 9845,
        video: false,
        poster_path: '/uprP8rtOgMYJQ2h3ldDFvGsaBgH.jpg',
        id: 77,
        adult: false,
        backdrop_path: '/q2CtXYjp9IlnfBcPktNkBPsuAEO.jpg',
        original_language: 'en',
        original_title: 'Memento',
        genre_ids: [9648, 53],
        title: 'Memento',
        vote_average: 8.2,
        overview:
            "Leonard Shelby is tracking down the man who raped and murdered his wife. The difficulty of locating his wife's killer, however, is compounded by the fact that he suffers from a rare, untreatable form of short-term memory loss. Although he can recall details of life before his accident, Leonard cannot remember what happened fifteen minutes ago, where he's going, or why.",
        release_date: '2000-10-11',
    },
    {
        popularity: 22.066,
        vote_count: 2,
        video: false,
        poster_path: '/oKrENAWxa7vd4haYmNxMXyuWxD7.jpg',
        id: 670426,
        adult: false,
        backdrop_path: null,
        original_language: 'en',
        original_title: 'Lucky',
        genre_ids: [53],
        title: 'Lucky',
        vote_average: 4.5,
        overview:
            'Lucky follows May, a self-help book author with all the answers, who suddenly finds herself stalked by a threatening but elusive masked man, and caught in a struggle to get help from the people around her and maintain control over her own life.',
        release_date: '2020-08-20',
    },
    {
        popularity: 28.122,
        vote_count: 632,
        video: false,
        poster_path: '/p9vCAVhDK375XyobVcKqzqzsUHE.jpg',
        id: 501907,
        adult: false,
        backdrop_path: '/w0tJot6O0UtLVBRIPAdg3dQ2oNO.jpg',
        original_language: 'en',
        original_title: 'A Beautiful Day in the Neighborhood',
        genre_ids: [18],
        title: 'A Beautiful Day in the Neighborhood',
        vote_average: 7,
        overview:
            "An award-winning cynical journalist, Lloyd Vogel, begrudgingly accepts an assignment to write an Esquire profile piece on the beloved television icon Fred Rogers. After his encounter with Rogers, Vogel's perspective on life is transformed.",
        release_date: '2019-09-07',
    },
    {
        popularity: 39.28,
        vote_count: 44,
        video: false,
        poster_path: '/sA154deR0X51EcR2lm2FfDczryg.jpg',
        id: 524047,
        adult: false,
        backdrop_path: '/juzEhsX92if2lJ2CSqKAI4RQswt.jpg',
        original_language: 'en',
        original_title: 'Greenland',
        genre_ids: [28, 878, 53],
        title: 'Greenland',
        vote_average: 6.3,
        overview:
            'A detached married couple must get their son and themselves to safety after being randomly selected to enter an underground bunker, as a massive object from space threatens to destroy the world in less than 48 hours.',
        release_date: '2020-07-29',
    },
    {
        popularity: 23.197,
        id: 149,
        video: false,
        vote_count: 2234,
        vote_average: 7.9,
        title: 'Akira',
        release_date: '1988-07-16',
        original_language: 'ja',
        original_title: 'アキラ',
        genre_ids: [878, 16],
        backdrop_path: '/qZ4NYuwME0j6QgJmIE6AZMgmCaj.jpg',
        adult: false,
        overview:
            'A secret military project endangers Neo-Tokyo when it turns a biker gang member into a rampaging psychic psychopath that only two teenagers and a group of psychics can stop.',
        poster_path: '/5KlRFKKSbyCiyYpZSS3A6G5bW0K.jpg',
    },
    {
        popularity: 21.003,
        vote_count: 2,
        video: false,
        poster_path: '/iwcAXsH8f5v56LbNdaZKdJbilz8.jpg',
        id: 722780,
        adult: false,
        backdrop_path: null,
        original_language: 'en',
        original_title: 'For the Sake of Vicious',
        genre_ids: [28, 27],
        title: 'For the Sake of Vicious',
        vote_average: 3.5,
        overview:
            'An innocent nurse, a tortured maniac and a suspicious hostage face off against a wave of violent intruders as they descend upon their place of refuge on Halloween night.',
        release_date: '2020-08-20',
    },
    {
        popularity: 22.754,
        vote_count: 329,
        video: false,
        poster_path: '/zGVbrulkupqpbwgiNedkJPyQum4.jpg',
        id: 592350,
        adult: false,
        backdrop_path: '/9guoVF7zayiiUq5ulKQpt375VIy.jpg',
        original_language: 'ja',
        original_title: '僕のヒーローアカデミア THE MOVIE ヒーローズ：ライジング',
        genre_ids: [28, 16],
        title: 'My Hero Academia: Heroes Rising',
        vote_average: 8.7,
        overview:
            "Class 1-A visits Nabu Island where they finally get to do some real hero work. The place is so peaceful that it's more like a vacation … until they're attacked by a villain with an unfathomable Quirk! His power is eerily familiar, and it looks like Shigaraki had a hand in the plan. But with All Might retired and citizens' lives on the line, there's no time for questions. Deku and his friends are the next generation of heroes, and they're the island's only hope.",
        release_date: '2019-12-20',
    },
    {
        popularity: 22.554,
        vote_count: 2,
        video: false,
        poster_path: '/iYkrn6iOH6lGYdCcBkyew1UYM5B.jpg',
        id: 585013,
        adult: false,
        backdrop_path: null,
        original_language: 'en',
        original_title: 'Shakespeare’s Shitstorm',
        genre_ids: [35],
        title: 'Shakespeare’s Shitstorm',
        vote_average: 4,
        overview:
            'Two decades after "Tromeo and Juliet", Lloyd Kaufman and The Troma Team go Back to The Bard for a TROMAtic adaptation of Shakespeare\'s "The Tempest".',
        release_date: '2020-08-20',
    },
    {
        popularity: 23.789,
        vote_count: 6535,
        video: false,
        poster_path: '/nR4LD4ZJg2n6LZQpcOrLFdMq0cD.jpg',
        id: 539,
        adult: false,
        backdrop_path: '/kZGaVeXSkkvrpMYvD97sxHj291k.jpg',
        original_language: 'en',
        original_title: 'Psycho',
        genre_ids: [18, 27, 53],
        title: 'Psycho',
        vote_average: 8.4,
        overview:
            'When larcenous real estate clerk Marion Crane goes on the lam with a wad of cash and hopes of starting a new life, she ends up at the notorious Bates Motel, where manager Norman Bates cares for his housebound mother.',
        release_date: '1960-06-22',
    },
    {
        popularity: 23.607,
        vote_count: 16,
        video: false,
        poster_path: '/hJUA4wfvw0A6l3niOfxourqpERA.jpg',
        id: 653598,
        adult: false,
        backdrop_path: '/nTyl9fqTQNtwh8BUTZ0WzKH16r7.jpg',
        original_language: 'en',
        original_title: 'Spree',
        genre_ids: [35, 27, 53],
        title: 'Spree',
        vote_average: 6.2,
        overview:
            'Kurt Kunkle, a rideshare driver thirsty for followers, has figured out a deadly plan to go viral. As his disturbing livestream is absurdly embraced by the social media hellscape, a comedienne emerges as the only hope to stop this rampage.',
        release_date: '2020-08-14',
    },
    {
        popularity: 26.029,
        vote_count: 2743,
        video: false,
        poster_path: '/yn5ihODtZ7ofn8pDYfxCmxh8AXI.jpg',
        id: 331482,
        adult: false,
        backdrop_path: '/lqxxwTRk0l7CubY6JkJdhnwJEkn.jpg',
        original_language: 'en',
        original_title: 'Little Women',
        genre_ids: [18, 10749],
        title: 'Little Women',
        vote_average: 8,
        overview: 'Four sisters come of age in America in the aftermath of the Civil War.',
        release_date: '2019-12-25',
    },
    {
        popularity: 24.66,
        vote_count: 3880,
        video: false,
        poster_path: '/2oRRTPNtozgPhOa9CYZiVl4GRQ5.jpg',
        id: 396535,
        adult: false,
        backdrop_path: '/5H8ftwrh0OzQ7QxTOixNqoMcIZs.jpg',
        original_language: 'ko',
        original_title: '부산행',
        genre_ids: [28, 27, 53],
        title: 'Train to Busan',
        vote_average: 7.7,
        overview:
            'Martial law is declared when a mysterious viral outbreak pushes Korea into a state of emergency. Those on an express train to Busan, a city that has successfully fended off the viral outbreak, must fight for their own survival…',
        release_date: '2016-07-20',
    },
    {
        popularity: 23.633,
        vote_count: 2,
        video: false,
        poster_path: null,
        id: 653221,
        adult: false,
        backdrop_path: null,
        original_language: 'ml',
        original_title: 'Hridayam',
        genre_ids: [],
        title: 'Hridayam',
        vote_average: 4,
        overview: 'Upcoming Malayalam Film',
        release_date: '2020-08-21',
    },
    {
        popularity: 26.449,
        vote_count: 46,
        video: false,
        poster_path: '/k50gYFDfpAyxcIGjWjnXAaOM81e.jpg',
        id: 505707,
        adult: false,
        backdrop_path: '/p71xHf9KBqEIP6gQZ53to2lDh4E.jpg',
        original_language: 'en',
        original_title: 'Waiting for the Barbarians',
        genre_ids: [18],
        title: 'Waiting for the Barbarians',
        vote_average: 5.4,
        overview:
            'At an isolated frontier outpost, a colonial magistrate suffers a crisis of conscience when an army colonel arrives looking to interrogate the locals about an impending uprising, using cruel tactics that horrify the magistrate.',
        release_date: '2019-09-06',
    },
    {
        popularity: 24.012,
        vote_count: 1,
        video: false,
        poster_path: '/t80bYCkLI0bOucXSPwlatY1ILYR.jpg',
        id: 679888,
        adult: false,
        backdrop_path: null,
        original_language: 'es',
        original_title: 'La boda de Rosa',
        genre_ids: [35],
        title: 'La boda de Rosa',
        vote_average: 6,
        overview:
            "Rosa is about to turn 45 and realises that she's always lived her life to serve everyone else. So she decides to leave it all behind and take charge of her life and fulfil her dream of starting her own business",
        release_date: '2020-08-21',
    },
    {
        popularity: 24.023,
        vote_count: 2,
        video: false,
        poster_path: '/1SDH760JhPQCTrIWH8ombqvIbBE.jpg',
        id: 612511,
        adult: false,
        backdrop_path: null,
        original_language: 'ja',
        original_title: '糸',
        genre_ids: [10749],
        title: 'Ito',
        vote_average: 3.5,
        overview:
            "Ren Takahashi and Aoi Sonoda were both born in 1989. They met for the first time at the age of 13 and became each other's first love, but they separated. At the age of 21, they met again. They were unable to undo their past. Now, they are 31-years-old.",
        release_date: '2020-08-21',
    },
    {
        popularity: 24.166,
        vote_count: 318,
        video: false,
        poster_path: '/ylPnfaphW3FrLBUVwAREVtiL9My.jpg',
        id: 529485,
        adult: false,
        backdrop_path: '/5mubFanEHVFJff4jLQH0uIOThMz.jpg',
        original_language: 'en',
        original_title: 'The Way Back',
        genre_ids: [18],
        title: 'The Way Back',
        vote_average: 6.6,
        overview:
            'A former basketball all-star, who has lost his wife and family foundation in a struggle with addiction attempts to regain his soul and salvation by becoming the coach of a disparate ethnically mixed high school basketball team at his alma mater.',
        release_date: '2020-03-05',
    },
    {
        popularity: 24.392,
        vote_count: 698,
        video: false,
        poster_path: '/7ht2IMGynDSVQGvAXhAb83DLET8.jpg',
        id: 565310,
        adult: false,
        backdrop_path: '/qfB3KR6AuRI3Sqz8jWAOpRaGC0H.jpg',
        original_language: 'en',
        original_title: 'The Farewell',
        genre_ids: [35, 18],
        title: 'The Farewell',
        vote_average: 7.6,
        overview:
            "A headstrong Chinese-American woman returns to China when her beloved grandmother is given a terminal diagnosis. Billi struggles with her family's decision to keep grandma in the dark about her own illness as they all stage an impromptu wedding to see grandma one last time.",
        release_date: '2019-07-12',
    },
    {
        popularity: 23.471,
        vote_count: 2,
        video: false,
        poster_path: '/xiyRr8Gh2RTHZwudKwYLX6XfgPp.jpg',
        id: 605503,
        adult: false,
        backdrop_path: '/7B5lk9T4rJeZsXyOlROHZShRJ35.jpg',
        original_language: 'bg',
        original_title: 'Бащата',
        genre_ids: [18],
        title: 'The Father',
        vote_average: 3.5,
        overview:
            'Vasil has just lost his long-time partner in life, his wife Ivanka. When a woman at her funeral proclaims that the dead woman called her cellphone, Vasil seeks out the help of a well-known psychic in order to try to contact his wife. His son Pavel tries to bring him to his senses, but Vasil stubbornly insists on doing things his own way… Following the internationally successful The Lesson and Glory, Grozeva and Valchanov return with an intimate family drama about the difficulties of connecting with those close to us. As the picture slowly gathers momentum, its story unfolds many of the carefully arranged absurd or comic situations typical for the Bulgarian filmmaking duo.',
        release_date: '2020-08-21',
    },
    {
        popularity: 23.383,
        vote_count: 2,
        video: false,
        poster_path: '/aI1HlPqotV33AhEBdd9swCzpMpk.jpg',
        id: 660369,
        adult: false,
        backdrop_path: '/szLnpU5huAsnTuHWt0ZQKiWafaE.jpg',
        original_language: 'fi',
        original_title: 'Neiti Aika',
        genre_ids: [99],
        title: 'Lady Time',
        vote_average: 4,
        overview:
            "Sirkka-Liisa died alone with no one left to miss her. Elina happened to buy her home after her death and ended up with all Sirkka-Liisa's possessions from books to photos. What would happen If Elina threw all her things away?",
        release_date: '2020-08-21',
    },
    {
        popularity: 31.527,
        vote_count: 1,
        video: false,
        poster_path: '/oN8XOrMb5piCUnbGy3p3qghx4Mj.jpg',
        id: 632632,
        adult: false,
        backdrop_path: '/u1wHUA0R48FH4WV3sGqjwx3aNZm.jpg',
        original_language: 'ja',
        original_title: '映画 ギヴン',
        genre_ids: [16, 18, 10402],
        title: 'Given',
        vote_average: 6,
        overview:
            'Following the airing of the final episode of the Given anime adaptation today in Japan, the official Twitter account announced that a feature film adaptation will be released in 2020 directly picking up where the TV series left off.',
        release_date: '2020-08-22',
    },
    {
        popularity: 21.062,
        vote_count: 7,
        video: false,
        poster_path: '/kdfvfqxhyqfdv3SO2XhOjkpaDUu.jpg',
        id: 566872,
        adult: false,
        backdrop_path: '/syiLP6ka3mggvMNj4e0ZxwSGRG2.jpg',
        original_language: 'en',
        original_title: 'The Burnt Orange Heresy',
        genre_ids: [18, 9648, 53],
        title: 'The Burnt Orange Heresy',
        vote_average: 5.4,
        overview:
            'Hired to steal a rare painting from one of most enigmatic painters of all time, an ambitious art dealer becomes consumed by his own greed and insecurity as the operation spins out of control.',
        release_date: '2020-03-06',
    },
    {
        popularity: 24.949,
        vote_count: 153,
        video: false,
        poster_path: '/akHIQu8W3rOgT28r25ggXaKcQIr.jpg',
        id: 480857,
        adult: false,
        backdrop_path: '/e7tjpKP36Xd6BzyTMZo4AUe86VM.jpg',
        original_language: 'en',
        original_title: 'Radioactive',
        genre_ids: [18, 36, 10749],
        title: 'Radioactive',
        vote_average: 6.2,
        overview:
            'Tells the story of Nobel Prize winner Marie Curie and her extraordinary scientific discoveries — through the prism of her marriage to husband Pierre — and the seismic and transformative effects their discovery of radium had on the 20th century.',
        release_date: '2020-03-11',
    },
    {
        popularity: 24.418,
        vote_count: 95,
        video: false,
        poster_path: '/aVbqhqYtlxwEGihTEhewZAgDOCX.jpg',
        id: 489326,
        adult: false,
        backdrop_path: '/dFB6Tiy3z2xRLbnEUB5ocApT5xG.jpg',
        original_language: 'en',
        original_title: 'Mortal',
        genre_ids: [28, 14, 53],
        title: 'Mortal',
        vote_average: 6.9,
        overview:
            'A young boy must discover the origins of his extraordinary powers before he is captured by authorities hell-bent on condemning him for an accidental murder.',
        release_date: '2020-02-28',
    },
    {
        popularity: 21.322,
        vote_count: 635,
        video: false,
        poster_path: '/4w1ItwCJCTtSi9nPfJC1vU6NIVg.jpg',
        id: 413518,
        adult: false,
        backdrop_path: '/AdqOBPw4PdtzOcfEuQuZ8MNeTKb.jpg',
        original_language: 'it',
        original_title: 'Pinocchio',
        genre_ids: [12, 18, 14, 10751],
        title: 'Pinocchio',
        vote_average: 6.8,
        overview:
            'In this live-action adaptation of the beloved fairytale, old woodcarver Geppetto fashions a wooden puppet, Pinocchio, who magically comes to life. Pinocchio longs for adventure and is easily led astray, encountering magical beasts, fantastical spectacles, while making friends and foes along his journey. However, his dream is to become a real boy, which can only come true if he finally changes his ways.',
        release_date: '2019-12-19',
    },
    {
        popularity: 23.124,
        vote_count: 5791,
        video: false,
        poster_path: '/h5Qz8J4T8YQnbZzHXM73WVYYVPK.jpg',
        id: 620,
        adult: false,
        backdrop_path: '/c6yfABGVKuB5cjoOwdX4AJMlzUz.jpg',
        original_language: 'en',
        original_title: 'Ghostbusters',
        genre_ids: [35, 14],
        title: 'Ghostbusters',
        vote_average: 7.4,
        overview:
            'After losing their academic posts at a prestigious university, a team of parapsychologists goes into business as proton-pack-toting "ghostbusters" who exterminate ghouls, hobgoblins and supernatural pests of all stripes. An ad campaign pays off when a knockout cellist hires the squad to purge her swanky digs of demons that appear to be living in her refrigerator.',
        release_date: '1984-06-08',
    },
    {
        popularity: 21.365,
        vote_count: 2,
        video: false,
        poster_path: '/87qlFoFQPMY6bD0MJnkJJYifjrT.jpg',
        id: 634233,
        adult: false,
        backdrop_path: '/iwIgSq0uOJA9oJd38XbjG5hiMg4.jpg',
        original_language: 'en',
        original_title: 'Class Action Park',
        genre_ids: [99],
        title: 'Class Action Park',
        vote_average: 3.5,
        overview:
            'Discover the legacy of Action Park, a very real amusement park that used to exist that has something of a legendary story. Not only because the park was wild and far less structured than something like Disneyland, but because many people were seriously injured, and some even died. While it sounds made up, this place was very real.',
        release_date: '2020-08-20',
    },
    {
        popularity: 22.92,
        vote_count: 50,
        video: false,
        poster_path: '/saxPKOrN6rNScTicLpBDZw58Cw.jpg',
        id: 586954,
        adult: false,
        backdrop_path: '/poKtpiQ0akacXzXohWmtb0Z7nFD.jpg',
        original_language: 'de',
        original_title: 'Latte Igel und der magische Wasserstein',
        genre_ids: [12, 16, 35, 10751],
        title: 'Latte and the Magic Waterstone',
        vote_average: 6.8,
        overview:
            'When a greedy bear steals a magic stone to keep the forest’s water for himself, a brave hedgehog and a timid squirrel must work together to retrieve it.',
        release_date: '2019-12-11',
    },
    {
        popularity: 20.836,
        vote_count: 92,
        video: false,
        poster_path: '/jBeL6pPUPo0wnyTmiuxPegcibPf.jpg',
        id: 608195,
        adult: false,
        backdrop_path: '/8LI4OEQGY2DIBTQQeRjYVKfL9Dl.jpg',
        original_language: 'en',
        original_title: 'Ghosts of War',
        genre_ids: [14, 27, 53, 10752],
        title: 'Ghosts of War',
        vote_average: 6,
        overview:
            'A group of World War II American soldiers encounter a supernatural enemy as they occupy a French castle previously under Nazi control.',
        release_date: '2020-07-03',
    },
    {
        popularity: 25.253,
        vote_count: 107,
        video: false,
        poster_path: '/yHsu8swJSgqDrsPiu7adBjOPLlp.jpg',
        id: 606679,
        adult: false,
        backdrop_path: '/aVX9a54YFmrcEHATubpuFQQKn5L.jpg',
        original_language: 'en',
        original_title: 'The High Note',
        genre_ids: [35, 18, 10402, 10749],
        title: 'The High Note',
        vote_average: 7.4,
        overview:
            'Set in the dazzling world of the LA music scene comes the story of Grace Davis, a superstar whose talent, and ego, have reached unbelievable heights. Maggie is Grace’s overworked personal assistant who’s stuck running errands, but still aspires to her childhood dream of becoming a music producer. When Grace’s manager presents her with a choice that could alter the course of her career, Maggie and Grace come up with a plan that could change their lives forever.',
        release_date: '2020-06-10',
    },
    {
        popularity: 20.291,
        vote_count: 213,
        video: false,
        poster_path: '/3xbjL0z8iH8e8L3USyeKGQrBfuZ.jpg',
        id: 533444,
        adult: false,
        backdrop_path: '/jQ06O9JAFN0VfDS4ezE09pfoj2h.jpg',
        original_language: 'en',
        original_title: 'Waves',
        genre_ids: [18, 10749],
        title: 'Waves',
        vote_average: 7.6,
        overview:
            'A controlling father’s attempts to ensure that his two children succeed in high school backfire after his son experiences a career-ending sports injury. Their familial bonds are eventually placed under severe strain by an unexpected tragedy.',
        release_date: '2019-11-15',
    },
    {
        popularity: 28.088,
        vote_count: 379,
        video: false,
        poster_path: '/vkwgzCBBiY3C1XEy0WakYfMOvnG.jpg',
        id: 548473,
        adult: false,
        backdrop_path: '/iyn2JQsftaqhQlXYaCCvn8udM5i.jpg',
        original_language: 'en',
        original_title: 'Color Out of Space',
        genre_ids: [27, 878],
        title: 'Color Out of Space',
        vote_average: 6.1,
        overview:
            'The Gardner family moves to a remote farmstead in rural New England to escape the hustle of the 21st century. They are busy adapting to their new life when a meteorite crashes into their front yard, melts into the earth, and infects both the land and the properties of space-time with a strange, otherworldly colour. To their horror, the family discovers this alien force is gradually mutating every life form that it touches—including them.',
        release_date: '2020-01-24',
    },
    {
        popularity: 23.38,
        vote_count: 385,
        video: false,
        poster_path: '/yake2myhbW7c6dKbmwYDy1i40bm.jpg',
        id: 474764,
        adult: false,
        backdrop_path: '/3h4vi71aicJDl13bODPPEl1bShr.jpg',
        original_language: 'en',
        original_title: 'The Lodge',
        genre_ids: [18, 27, 53],
        title: 'The Lodge',
        vote_average: 6.1,
        overview:
            "When a father is forced to abruptly depart for work, he leaves his children, Aidan and Mia, at their holiday home in the care of his new girlfriend, Grace. Isolated and alone, a blizzard traps them inside the lodge as terrifying events summon specters from Grace's dark past.",
        release_date: '2019-01-25',
    },
    {
        popularity: 23.221,
        id: 463257,
        video: false,
        vote_count: 497,
        vote_average: 7.4,
        title: 'The Peanut Butter Falcon',
        release_date: '2019-08-09',
        original_language: 'en',
        original_title: 'The Peanut Butter Falcon',
        genre_ids: [12, 18, 35],
        backdrop_path: '/4NJ9Wbib4YfvnZyyvV8WSLOAQUh.jpg',
        adult: false,
        overview:
            'A down-on-his-luck crab fisherman embarks on a journey to get a young man with Down syndrome to a professional wrestling school in rural North Carolina and away from the retirement home where he’s lived for the past two and a half years.',
        poster_path: '/qyQcRGvdW3VtxHR4fSDgPOePEip.jpg',
    },
    {
        popularity: 26.571,
        vote_count: 586,
        video: false,
        poster_path: '/mBBBXseq4k4dI63k06XIrsc02j8.jpg',
        id: 542224,
        adult: false,
        backdrop_path: '/jEPEVO48hKQB0EUNFQOSv6qtKNW.jpg',
        original_language: 'en',
        original_title: 'Gretel & Hansel',
        genre_ids: [14, 27, 53],
        title: 'Gretel & Hansel',
        vote_average: 6.2,
        overview:
            'A long time ago in a distant fairy tale countryside, a young girl leads her little brother into a dark wood in desperate search of food and work, only to stumble upon a nexus of terrifying evil.',
        release_date: '2020-01-30',
    },
    {
        popularity: 20.59,
        vote_count: 852,
        video: false,
        poster_path: '/2kNnf7BwRCEm4bcFkdiE0T4U25s.jpg',
        id: 457335,
        adult: false,
        backdrop_path: '/fssCO59bqU5f0zngeYKex0g1vyb.jpg',
        original_language: 'en',
        original_title: 'Guns Akimbo',
        genre_ids: [28, 35],
        title: 'Guns Akimbo',
        vote_average: 6.4,
        overview:
            'An ordinary guy suddenly finds himself forced to fight a gladiator-like battle for a dark website that streams the violence for viewers. Miles must fight heavily armed Nix and also save his kidnapped ex-girlfriend.',
        release_date: '2019-09-09',
    },
    {
        popularity: 26.449,
        vote_count: 0,
        video: false,
        poster_path: '/6wOCmFswyp4Xp1B3LHShE2FdIXT.jpg',
        id: 732374,
        adult: false,
        backdrop_path: null,
        original_language: 'es',
        original_title: 'Agua del este',
        genre_ids: [18, 9648],
        title: 'Agua del este',
        vote_average: 0,
        overview:
            'Pablo, after five years of the death of his wife, returns to the hotel of his family in Puelo with the objective to close that painful wound. During this trip, he reconnects with people from his childhood and also meets Ana, the new hotel manager, who becomes his spiritual guide to reconcile Pablo with nature, which was the cause of his wife’s passing.',
        release_date: '2020-08-22',
    },
    {
        popularity: 20.339,
        vote_count: 103,
        video: false,
        poster_path: '/cdqZqIcWt0Ne2Io2OA9iWqqMuCA.jpg',
        id: 589049,
        adult: false,
        backdrop_path: '/kU5qE5b6ksL3osaqKCUlMS08Ays.jpg',
        original_language: 'en',
        original_title: 'The Photograph',
        genre_ids: [18, 10749],
        title: 'The Photograph',
        vote_average: 6.9,
        overview:
            "When famed photographer Christina Eames dies unexpectedly, she leaves her estranged daughter, Mae, hurt, angry and full of questions. When Mae finds a photograph tucked away in a safe-deposit box, she soon finds herself delving into her mother's early life -- an investigation that leads to an unexpected romance with a rising journalist.",
        release_date: '2020-02-14',
    },
    {
        popularity: 20.104,
        vote_count: 571,
        video: false,
        poster_path: '/myf3qzpeN0JbuFRPwSpJcz7rmAT.jpg',
        id: 458305,
        adult: false,
        backdrop_path: '/jZ4YdDCnfK4cO13do9J4JaT8d2O.jpg',
        original_language: 'en',
        original_title: 'Vivarium',
        genre_ids: [27, 878, 53],
        title: 'Vivarium',
        vote_average: 5.9,
        overview:
            'A young woman and her fiancé are in search of the perfect starter home. After following a mysterious real estate agent to a new housing development, the couple finds themselves trapped in a maze of identical houses and forced to raise an otherworldly child.',
        release_date: '2019-09-07',
    },
    {
        popularity: 25.035,
        vote_count: 0,
        video: false,
        poster_path: '/ggrMLoVTrBKgGh7UyAhXFuAZCNF.jpg',
        id: 605133,
        adult: false,
        backdrop_path: null,
        original_language: 'en',
        original_title: 'Slaxx',
        genre_ids: [35, 27],
        title: 'Slaxx',
        vote_average: 0,
        overview:
            'When a possessed pair of jeans begins to kill the staff of a trendy clothing store, it is up to Libby, an idealistic young salesclerk, to stop its bloody rampage.',
        release_date: '2020-08-23',
    },
    {
        popularity: 23.572,
        vote_count: 994,
        video: false,
        poster_path: '/79vujbsWEbX4dzffBV541QXN6sf.jpg',
        id: 10494,
        adult: false,
        backdrop_path: '/e8Wt7n3QEu6wlZONUDjJuNusptl.jpg',
        original_language: 'ja',
        original_title: 'パーフェクトブルー',
        genre_ids: [16, 53],
        title: 'Perfect Blue',
        vote_average: 8.2,
        overview:
            "A retired pop singer turned actress' sense of reality is shaken when she is stalked by an obsessed fan and seemingly a ghost of her past.",
        release_date: '1997-07-25',
    },
    {
        popularity: 21.407,
        vote_count: 124,
        video: false,
        poster_path: '/41YWD0M32uo6ekBEvVrQgidyemB.jpg',
        id: 478860,
        adult: false,
        backdrop_path: '/e8Cqw8U7vCcMrH1dHYZT9O01Jiy.jpg',
        original_language: 'fr',
        original_title: 'Proxima',
        genre_ids: [18],
        title: 'Proxima',
        vote_average: 6.5,
        overview:
            'Sarah is a French astronaut training at the European Space Agency in Cologne. She is the only woman in the arduous program. She lives alone with Stella, her seven year old daughter. Sarah feels guilty that she cannot spend more time with her child. Her love is overpowering, unsettling. When Sarah is chosen to join the crew of a year-long space mission called Proxima, it creates chaos in the mother-daughter relationship.',
        release_date: '2019-11-27',
    },
    {
        popularity: 20.664,
        vote_count: 0,
        video: false,
        poster_path: '/yC1bNisYFgREyCIPmph0cbr03PG.jpg',
        id: 732446,
        adult: false,
        backdrop_path: null,
        original_language: 'en',
        original_title: 'Locus Suspectus',
        genre_ids: [],
        title: 'Locus Suspectus',
        vote_average: 0,
        overview:
            'Eroding ideologies shift sands of unreality.  Shadow cast narratives reflecting surface.  Polarizing algorithms weathering perceptions.  The organism creates the environment.  Return to the elements.',
        release_date: '2020-08-22',
    },
    {
        popularity: 20.65,
        vote_count: 382,
        video: false,
        poster_path: '/8GGS0jkFFCnmdStvZED6NL6V7gd.jpg',
        id: 502425,
        adult: false,
        backdrop_path: '/kolkVKNZSjhZGHwcrFU36Watpke.jpg',
        original_language: 'en',
        original_title: 'Escape from Pretoria',
        genre_ids: [18, 36, 53],
        title: 'Escape from Pretoria',
        vote_average: 7.3,
        overview:
            'South Africa, 1978. Tim Jenkin and Stephen Lee, two white political activists from the African National Congress imprisoned by the apartheid regime, put a plan in motion to escape from the infamous Pretoria Prison.',
        release_date: '2020-03-06',
    },
    {
        popularity: 20.614,
        vote_count: 8,
        video: false,
        poster_path: '/wb2VpOZTSINPI7jQww0fYCEppcE.jpg',
        id: 526973,
        adult: false,
        backdrop_path: '/91PzB8FwABrdgQzQGTDgxo2xFnJ.jpg',
        original_language: 'en',
        original_title: 'Target Number One',
        genre_ids: [80, 53],
        title: 'Target Number One',
        vote_average: 6.1,
        overview:
            'Ex heroin junkie, Daniel Léger, gets involved in a drug deal with the wrong people for the wrong reasons. When the deal goes sour, Daniel gets thrown into a Thai prison and slapped with a 100-year sentence. While he tries to survive his Bangkok incarceration, the news of his conviction captures the attention of Globe and Mail journalist Victor Malarek, who decides to go after the shady undercover cops responsible for wrongly accusing Daniel.',
        release_date: '2020-07-10',
    },
];

const genres = {
    Action: 28,
    Adventure: 12,
    Animation: 16,
    Comedy: 35,
    Crime: 80,
    Documentary: 99,
    Drama: 18,
    Family: 10751,
    Fantasy: 14,
    History: 36,
    Horror: 27,
    Music: 10402,
    Mystery: 9648,
    Romance: 10749,
    'Science Fiction': 878,
    'TV Movie': 10770,
    Thriller: 53,
    War: 10752,
    Western: 37,
};

const $buttonContainer = document.querySelector('.button-container');
const $movielist = document.querySelector('.movielist');
const $message = document.querySelector('.message');
const $modalOverlay = document.querySelector('.modal-overlay');
const $modal = document.querySelector('.modal');
const $modalExitButton = document.querySelector('.modal-exit-button');

function filterMovie(movies, genreIds) {
    let filteredMovies = movies.slice();
    if (genreIds) {
        genreIds.forEach((id) => {
            filteredMovies = filteredMovies.filter((movie) => movie.genre_ids.includes(id));
        });
    }
    console.log(filteredMovies);
    renderMovies(filteredMovies);
}

function renderMovies(movies) {
    const $movies = movies.map((movie) => makeMovieBox(movie));
    $movielist.innerHTML = '';
    $movielist.append(...$movies);
    setMessage(movies);
}

function setMessage(movies) {
    $message.textContent = `Find ${movies.length} movies 🎥`;
}

function makeMovieBox(movie) {
    const $movie = document.createElement('div');
    $movie.className = 'movie';
    $movie.dataset.id = movie.id;
    if (movie.poster_path) {
        $movie.style.background = `url(https://image.tmdb.org/t/p/w200${movie.poster_path}) no-repeat 0 0 / cover`;
    } else $movie.style.backgroundColor = 'rgba(0, 0, 0, 0.7)';

    const $title = document.createElement('span');
    $title.className = 'contents title';
    $title.textContent = movie.title;

    const $rating = document.createElement('span');
    $rating.className = 'contents rating';
    $rating.textContent = `⭐${movie.vote_average}`;

    const $released = document.createElement('span');
    $released.className = 'contents released';
    $released.textContent = movie.release_date.split('-').join('.');
    $movie.append($title, $released, $rating);

    return $movie;
}

function checkGenres() {
    const $buttons = document.querySelectorAll('button');
    const genreIds = Array.from($buttons)
        .filter(($button) => $button.classList.contains('clicked'))
        .map(($button) => genres[$button.textContent]);
    return genreIds;
}

function handleClickButton(e) {
    const { target } = e;
    if (target.tagName === 'BUTTON') {
        if (target.classList.contains('clicked')) {
            target.classList.remove('clicked');
        } else {
            target.classList.add('clicked');
        }
        filterMovie(movies, checkGenres());
    }
}

function makeModal(movie) {
    const $poster = document.querySelector('.poster');
    if (movie.poster_path) {
        $poster.style.background = `url(https://image.tmdb.org/t/p/w200${movie.poster_path}) no-repeat 0 0 / cover`;
    } else $poster.style.backgroundColor = 'rgba(0, 0, 0, 0.7)';

    const $title = document.querySelector('.modal-title');
    $title.textContent =
        movie.title === movie.original_title
            ? movie.title
            : `${movie.title}(${movie.original_title})`;

    const $detail = document.querySelector('.detail');
    $detail.innerHTML = `${movie.release_date
        .split('-')
        .join('.')}<span class="divider">|</span>⭐ ${
        movie.vote_average
    }<span class="divider">|</span><span title="vote count">${movie.vote_count}</span>`;

    const $overview = document.querySelector('.overview');
    $overview.textContent = movie.overview;

    $modal.style.top = `${document.documentElement.scrollTop}px`;
    document.body.style.overflow = 'hidden';
    $modalOverlay.classList.remove('hidden');
    $modal.classList.remove('hidden');
}

function handleClickMovie(e) {
    const { target } = e;
    console.log(target);
    let movieId;
    if (target.classList.contains('movie')) {
        movieId = target.dataset.id;
    } else if (target.classList.contains('contents')) {
        movieId = target.parentElement.dataset.id;
    }
    console.log(movieId);
    const clickedMovie = movies.filter((movie) => movie.id === Number(movieId))[0];
    makeModal(clickedMovie);
}

function handleExitModal() {
    $modalOverlay.classList.add('hidden');
    $modal.classList.add('hidden');
    document.body.style.overflow = 'visible';
}

function init() {
    renderMovies(movies);
    $buttonContainer.addEventListener('click', handleClickButton);
    $movielist.addEventListener('click', handleClickMovie);
    $modalOverlay.addEventListener('click', handleExitModal);
    $modalExitButton.addEventListener('click', handleExitModal);
}

init();
